version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=locacao
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123@123

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code 
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=locacao
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123@123
    depends_on:
      - db 

volumes:
  postgres_data: