# Generated by Django 4.2.5 on 2025-10-06 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='hora_fim',
            new_name='horario_fim',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='hora_inicio',
            new_name='horario_inicio',
        ),
    ]
