# Generated by Django 4.2.5 on 2025-10-06 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_hora_fim_reserva_horario_fim_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='horario_fim',
            new_name='horario_termino',
        ),
    ]
